

import numpy, os, cv2, sys, time, math, functools

#from MAVProxy.modules.lib import mp_image
#from MAVProxy.modules.mavproxy_map import mp_slipmap
#from MAVProxy.modules.lib.mp_menu import *
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):

    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(944, 547)
        self.setWindowIcon(QtGui.QIcon('canberrauav_logo.jpg'))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.image_in_2 = QtGui.QGraphicsView(self.centralwidget)
        self.image_in_2.setGeometry(QtCore.QRect(430, 70, 131, 91))
        self.image_in_2.setObjectName(_fromUtf8("image_in_2"))
        self.image_in_1 = QtGui.QGraphicsView(self.centralwidget)
        self.image_in_1.setGeometry(QtCore.QRect(570, 70, 131, 91))
        self.image_in_1.setObjectName(_fromUtf8("image_in_1"))
        self.image_in_4 = QtGui.QGraphicsView(self.centralwidget)
        self.image_in_4.setGeometry(QtCore.QRect(150, 70, 131, 91))
        self.image_in_4.setObjectName(_fromUtf8("image_in_4"))
        self.image_in_5 = QtGui.QGraphicsView(self.centralwidget)
        self.image_in_5.setGeometry(QtCore.QRect(10, 70, 131, 91))
        self.image_in_5.setObjectName(_fromUtf8("image_in_5"))
        self.image_in_3 = QtGui.QGraphicsView(self.centralwidget)
        self.image_in_3.setGeometry(QtCore.QRect(290, 70, 131, 91))
        self.image_in_3.setObjectName(_fromUtf8("image_in_3"))
        self.image_2nd = QtGui.QGraphicsView(self.centralwidget)
        self.image_2nd.setGeometry(QtCore.QRect(570, 410, 131, 91))
        self.image_2nd.setObjectName(_fromUtf8("image_2nd"))
        self.image_3rd = QtGui.QGraphicsView(self.centralwidget)
        self.image_3rd.setGeometry(QtCore.QRect(430, 410, 131, 91))
        self.image_3rd.setObjectName(_fromUtf8("image_3rd"))
        self.image_6th = QtGui.QGraphicsView(self.centralwidget)
        self.image_6th.setGeometry(QtCore.QRect(10, 410, 131, 91))
        self.image_6th.setObjectName(_fromUtf8("image_6th"))
        self.image_5th = QtGui.QGraphicsView(self.centralwidget)
        self.image_5th.setGeometry(QtCore.QRect(150, 410, 131, 91))
        self.image_5th.setObjectName(_fromUtf8("image_5th"))
        self.image_4th = QtGui.QGraphicsView(self.centralwidget)
        self.image_4th.setGeometry(QtCore.QRect(290, 410, 131, 91))
        self.image_4th.setObjectName(_fromUtf8("image_4th"))
        self.map_view = QtGui.QGraphicsView(self.centralwidget)
        self.map_view.setGeometry(QtCore.QRect(430, 170, 271, 231))
        self.map_view.setObjectName(_fromUtf8("map_view"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(710, 70, 211, 431))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Flight = QtGui.QWidget()
        self.Flight.setObjectName(_fromUtf8("Flight"))
        self.pushButton = QtGui.QPushButton(self.Flight)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 89, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.Flight)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 90, 89, 25))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.Flight)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 150, 89, 25))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.Flight)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 120, 89, 25))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.Flight)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 180, 89, 25))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.Flight)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 150, 89, 25))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.Flight)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 120, 89, 25))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.Flight)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 180, 89, 25))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.Horizon_widget = QtGui.QWidget(self.Flight)
        self.Horizon_widget.setGeometry(QtCore.QRect(10, 240, 191, 161))
        self.Horizon_widget.setAutoFillBackground(True)
        self.Horizon_widget.setObjectName(_fromUtf8("Horizon_widget"))
        self.pushButton_9 = QtGui.QPushButton(self.Flight)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 210, 89, 25))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.Flight)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 210, 89, 25))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.label_5 = QtGui.QLabel(self.Flight)
        self.label_5.setGeometry(QtCore.QRect(13, 67, 81, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_7 = QtGui.QLabel(self.Flight)
        self.label_7.setGeometry(QtCore.QRect(110, 67, 81, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_11 = QtGui.QPushButton(self.Flight)
        self.pushButton_11.setGeometry(QtCore.QRect(3, 4, 201, 61))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.tabWidget.addTab(self.Flight, _fromUtf8(""))
        self.kill_slider = QtGui.QWidget()
        self.kill_slider.setObjectName(_fromUtf8("kill_slider"))
        self.verticalSlider = QtGui.QSlider(self.kill_slider)
        self.verticalSlider.setGeometry(QtCore.QRect(80, 70, 41, 321))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.label_8 = QtGui.QLabel(self.kill_slider)
        self.label_8.setGeometry(QtCore.QRect(33, 5, 141, 61))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.kill_slider, _fromUtf8(""))
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(289, 290, 131, 111))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.lcd_batt_pct = QtGui.QLCDNumber(self.widget_2)
        self.lcd_batt_pct.setGeometry(QtCore.QRect(0, 0, 131, 51))
        self.lcd_batt_pct.setDigitCount(3)
        self.lcd_batt_pct.setObjectName(_fromUtf8("lcd_batt_pct"))
        self.lcd_fuel_pct = QtGui.QLCDNumber(self.widget_2)
        self.lcd_fuel_pct.setGeometry(QtCore.QRect(0, 60, 131, 51))
        self.lcd_fuel_pct.setDigitCount(3)
        self.lcd_fuel_pct.setObjectName(_fromUtf8("lcd_fuel_pct"))
        self.label_3 = QtGui.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(4, 33, 67, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(3, 93, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.image_1st = QtGui.QGraphicsView(self.centralwidget)
        self.image_1st.setGeometry(QtCore.QRect(10, 170, 271, 231))
        self.image_1st.setObjectName(_fromUtf8("image_1st"))
        self.widget_5 = QtGui.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(290, 170, 131, 111))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.lcd_speed_kts = QtGui.QLCDNumber(self.widget_5)
        self.lcd_speed_kts.setGeometry(QtCore.QRect(0, 0, 131, 51))
        self.lcd_speed_kts.setDigitCount(3)
        self.lcd_speed_kts.setObjectName(_fromUtf8("lcd_speed_kts"))
        self.lcd_alt_ft = QtGui.QLCDNumber(self.widget_5)
        self.lcd_alt_ft.setGeometry(QtCore.QRect(0, 60, 131, 51))
        self.lcd_alt_ft.setDigitCount(3)
        self.lcd_alt_ft.setObjectName(_fromUtf8("lcd_alt_ft"))
        self.label = QtGui.QLabel(self.widget_5)
        self.label.setGeometry(QtCore.QRect(4, 32, 67, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.widget_5)
        self.label_2.setGeometry(QtCore.QRect(5, 93, 81, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 641, 51))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCUAV_Search_Viewer = QtGui.QMenu(self.menubar)
        self.menuCUAV_Search_Viewer.setObjectName(_fromUtf8("menuCUAV_Search_Viewer"))
        self.menuModules = QtGui.QMenu(self.menubar)
        self.menuModules.setObjectName(_fromUtf8("menuModules"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuOutput = QtGui.QMenu(self.menubar)
        self.menuOutput.setObjectName(_fromUtf8("menuOutput"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionOutback_Challenge = QtGui.QAction(MainWindow)
        self.actionOutback_Challenge.setObjectName(_fromUtf8("actionOutback_Challenge"))
        self.actionSITL = QtGui.QAction(MainWindow)
        self.actionSITL.setObjectName(_fromUtf8("actionSITL"))
        self.actionDevelopment = QtGui.QAction(MainWindow)
        self.actionDevelopment.setObjectName(_fromUtf8("actionDevelopment"))
        self.actionHorizon = QtGui.QAction(MainWindow)
        self.actionHorizon.setObjectName(_fromUtf8("actionHorizon"))
        self.actionMap = QtGui.QAction(MainWindow)
        self.actionMap.setObjectName(_fromUtf8("actionMap"))
        self.actionConsole = QtGui.QAction(MainWindow)
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSearch = QtGui.QAction(MainWindow)
        self.actionSearch.setObjectName(_fromUtf8("actionSearch"))
        self.actionOnline = QtGui.QAction(MainWindow)
        self.actionOnline.setObjectName(_fromUtf8("actionOnline"))
        self.menuCUAV_Search_Viewer.addAction(self.actionOpen)
        self.menuCUAV_Search_Viewer.addAction(self.actionSave)
        self.menuCUAV_Search_Viewer.addAction(self.actionExit)
        self.menuModules.addAction(self.actionHorizon)
        self.menuModules.addAction(self.actionMap)
        self.menuModules.addAction(self.actionConsole)
        self.menuView.addAction(self.actionOutback_Challenge)
        self.menuView.addAction(self.actionSITL)
        self.menuView.addAction(self.actionDevelopment)
        self.menuHelp.addAction(self.actionSearch)
        self.menuHelp.addAction(self.actionOnline)
        self.menubar.addAction(self.menuCUAV_Search_Viewer.menuAction())
        self.menubar.addAction(self.menuModules.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuOutput.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CanberraUAV Mission Viewer", None))
        self.pushButton.setText(_translate("MainWindow", "Arm", None))
        self.pushButton_2.setText(_translate("MainWindow", "Arm", None))
        self.pushButton_3.setText(_translate("MainWindow", "Loiter", None))
        self.pushButton_4.setText(_translate("MainWindow", "Auto", None))
        self.pushButton_5.setText(_translate("MainWindow", "Return", None))
        self.pushButton_6.setText(_translate("MainWindow", "Loiter", None))
        self.pushButton_7.setText(_translate("MainWindow", "Auto", None))
        self.pushButton_8.setText(_translate("MainWindow", "Return", None))
        self.pushButton_9.setText(_translate("MainWindow", "Land", None))
        self.pushButton_10.setText(_translate("MainWindow", "Land", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Porter</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Kraken</span></p></body></html>", None))
        self.pushButton_11.setText(_translate("MainWindow", "OBC START", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Flight), _translate("MainWindow", "Flight", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Flight</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Termination</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kill_slider), _translate("MainWindow", "Kill", None))
        self.label_3.setText(_translate("MainWindow", "Battery %", None))
        self.label_4.setText(_translate("MainWindow", "Fuel %", None))
        self.label.setText(_translate("MainWindow", "Speed kts", None))
        self.label_2.setText(_translate("MainWindow", "Altitude ft", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/ArduPilot.png\"/></p></body></html>", None))
        self.menuCUAV_Search_Viewer.setTitle(_translate("MainWindow", "File", None))
        self.menuModules.setTitle(_translate("MainWindow", "Modules", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuOutput.setTitle(_translate("MainWindow", "Output", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionOutback_Challenge.setText(_translate("MainWindow", "Outback Challenge", None))
        self.actionSITL.setText(_translate("MainWindow", "SITL", None))
        self.actionDevelopment.setText(_translate("MainWindow", "Development", None))
        self.actionHorizon.setText(_translate("MainWindow", "Horizon", None))
        self.actionMap.setText(_translate("MainWindow", "Map", None))
        self.actionConsole.setText(_translate("MainWindow", "Console", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSearch.setText(_translate("MainWindow", "Search", None))
        self.actionOnline.setText(_translate("MainWindow", "Online", None))

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_MainWindow()
    ex.show()
    sys.exit(app.exec_())

import images_rc
